#!# perl: code/access
use strict;
use warnings;
use YAML::XS;

BEGIN{
    use FindBin qw( $RealBin );
    use lib "$RealBin/../lib";
};
use Access;

my $access = Access->new( path => "$RealBin/../../etc/dashboard/access" );

return sub
{
    die "username undef" unless my $username = shift;
    return $access->accesss( $username );
};

