#!/usr/bin/env perl
use strict;
use warnings;

use YAML::XS;
use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 [--user username] [--add work||--del root] [--node 10.10.1.1]
    
=cut

BEGIN{
    use FindBin qw( $RealBin );
    use lib "$RealBin/../lib";
};
use Node;

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( user=s add=s del=s node=s ) )->dump();
#$option->assert(qw( script package output ));

my $node = Node->new( path => "$RealBin/../../etc/dashboard/node" );

unless( $o{user} )
{
    YAML::XS::DumpFile \*STDOUT, $node->users();
    exit;
}

unless( $o{add} || $o{del} )
{
    YAML::XS::DumpFile \*STDOUT, $node->nodes( $o{user} );
    exit;
}


my @node = ( $o{node} ) if $o{node};

unless( $o{node} )
{
    while( <STDIN> )
    {
        chomp $_;
        push @node, $_;
    }
}

$o{add} ? $node->add( $o{user}  => \@node, $o{add} ) : $node->del( $o{user} => \@node, $o{del} );
