#!/usr/bin/env perl
use strict;
use warnings;

use MYDan::Util::OptConf;

=head1 SYNOPSIS

 $0 [--user username] [--add||--del] [--node 10.10.1.1]
    
=cut

BEGIN{
    use FindBin qw( $RealBin );
    use lib "$RealBin/../lib";
};
use Node;

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( user=s add del node=s ) )->dump();
#$option->assert(qw( script package output ));

my $node = Node->new( path => "$RealBin/../../etc/dashboard/node" );

unless( $o{user} )
{
    map{ print "$_\n" }$node->users();
    exit;
}

unless( $o{add} || $o{del} )
{
    map{ print "$_\n" }$node->nodes( $o{user} );
    exit;
}


my @node = ( $o{node} ) if $o{node};

unless( $o{node} )
{
    while( <STDIN> )
    {
        chomp $_;
        push @node, $_;
    }
}

$o{add} ? $node->add( $o{user}  => \@node ) : $node->del( $o{user} => \@node );
