#!/usr/bin/env perl
use strict;
use warnings;


=head1 SYNOPSIS

 $0 [--user username] [--add||--del] [--node 10.10.1.1]
    
=cut


my $code = do "../code/node";
print ref $code;


my @x = &$code( shift );
use Data::Dumper;
print Dumper \@x;
